repos:

  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        args: [--line-length=110]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.9
    hooks:
    - id: flake8

  - repo: local
    hooks:
    -   id: publish_notebook
        name: publish_notebook
        entry: publish_notebook.sh
        language: script
        types: ["file", "non-executable", "text"]
        exclude: ^source/

