repos:

  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        args: [--line-length=84]
        language_version: python3.7

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: flake8

  - repo: local
    hooks:
    -   id: publish_notebook
        name: publish_notebook
        entry: publish_notebook.sh
        language: script
        types: ["file", "non-executable", "text"]
        exclude: ^source/

