repos:

  - repo: https://github.com/ambv/black
    rev: stable
    hooks:
      - id: black
        args: [--line-length=84]
        language_version: python3.7

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: flake8

  # - repo: https://gitlab.com/iamlikeme/nbhooks
  #   rev: 1.0.0  # Set to the most recent version
  #   hooks:
  #     - id: nb-ensure-clean
  #       args: [--meta, ExecuteTime]  # Optional blacklist of metadata keys (you can use regex)

