# This is a basic workflow to help you get started with Actions

name: Linter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Super-Linter
      uses: github/super-linter@v3.2.0
      env:
          VALIDATE_ALL_CODEBASE: false
 
